server:
  port: 58001
eureka:
  instance:
    hostname: register1
    prefer-ip-address: false #集群时,必须为false
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
   
  server:
    enable-self-preservation: false
    peer-eureka-nodes-update-interval-ms: 600000 #集群里eureka节点的变化信息更新的时间间隔，单位为毫秒，默认为10 * 60 * 1000
    PeerEurekaStatusRefreshTimeIntervalMs: 30000 #服务器节点的状态信息被更新的时间间隔，单位为毫秒，默认为30 * 1000
    WaitTimeInMsWhenSyncEmpty: 300000 #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
    eviction-interval-timer-in-ms: 60000  # 清理无效节点间隔（单位毫秒，默认是60*1000）
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://register2:58002/eureka/