server:
  port: 8761
eureka:
  instance:
    hostname: 130.232.3.254
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/